<a href="https://colab.research.google.com/github/sakshitiwari1234/Data-Science-/blob/main/numpyclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [ ]:
import numpy  as np

In [ ]:
arr  = np.array([2,3,4,5,43])

In [ ]:
print(arr)

[ 2  3  4  5 43]


In [ ]:
print(np.__version__)

1.23.5


In [ ]:
sakshi = np.array((2,3,4,5,6,7))
print(sakshi)

[2 3 4 5 6 7]


In [ ]:
arr  = np.array([[2,3,4,5,43],[2,34,5,6,2]])
print(arr)
print(arr.ndim)

[[ 2  3  4  5 43]
 [ 2 34  5  6  2]]
2


In [ ]:
print(arr)

[ 2  3  4  5 43]


In [ ]:
arr  = np.array([[2,3,4,5,43],[2,34,5,6,2]])
print(arr)

[[ 2  3  4  5 43]
 [ 2 34  5  6  2]]


In [ ]:
#creating three dimensions array
myarr = np.array([[[2,3],[2,4],[5,6]]])
print(myarr)


[[[2 3]
  [2 4]
  [5 6]]]


In [ ]:
print(type(myarr))
print(myarr.size)

<class 'numpy.ndarray'>
6


In [ ]:
print(myarr.ndim)

3


# New Section

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
hey = np.array([97,54,3,21], ndmin=7)
print(hey)

print("number of dimensions are:", hey.ndim)

In [ ]:
hey = np.array([97,54,3,21])
print(hey)


[97 54  3 21]


In [ ]:
print(hey[2], hey[0])

3 97


In [ ]:
arr  = np.array([[2,3,4,5,43],[2,34,5,6,2]])
print(arr)

[[ 2  3  4  5 43]
 [ 2 34  5  6  2]]


In [ ]:
print("1st row 4th elemtn:", arr[0,1])
print("1st row 4th elemtn:", arr[1,2])



1st row 4th elemtn: 3
1st row 4th elemtn: 5


In [ ]:
#creating three dimensions array
myarr = np.array([[[2,3],[2,4],[5,6]]])
print(myarr)


[[[2 3]
  [2 4]
  [5 6]]]


In [ ]:
print(myarr[1,2,1])

IndexError: index 1 is out of bounds for axis 0 with size 1

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [ ]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(arr[0,1, 1])

5
